### ISSUE TITLE
style filter drop-down

### ISSUE THREAD

**Issue by vivkay** [algonquindesign-grads/2016#111]
Hi @thomasjbradley,

Not sure how to style this drop-down element. It looks like default styling, and I read a couple of blogs saying that it could not be easily styled. Know any tricks?

![screen shot 2016-02-28 at 9 33 48 am](https://cloud.githubusercontent.com/assets/6340292/13379853/fba37378-ddff-11e5-9833-09bec67d6583.png)

The other buttons are styled (but their styles don't automatically get adopted by the drop-down I noticed, so I can't just change it in a media query can I?)

![screen shot 2016-02-28 at 9 40 37 am](https://cloud.githubusercontent.com/assets/6340292/13379856/1658c344-de00-11e5-963f-7d977ab6f84b.png)

Thank you!

**Comment by thomasjbradley** [comment]
Don't style it. It's a default control and is usable by people because it's recognizable.
It's also a common pattern to use a default `<select>` box for navigation and filters on small screens.

**Comment by vivkay** [comment]
sounds good, thanks @thomasjbradley ! :palm_tree:
