### ISSUE TITLE
All placeholder text/images are removed from website (Content & usability)

### ISSUE THREAD

**Issue by natalie-macpherson** [algonquindesign-grads/2016#114]

**Comment by dagerebe** [comment]
This has been completed by people other than myself.

**Comment by natalie-macpherson** [comment]
There are still placeholder images in the footer. They will be removed once we get all the logos for our sponsors

**Comment by ccmadrid** [comment]
placeholder videos need to be replaced too guys

**Comment by natalie-macpherson** [comment]
@ccmadrid  They video might be on vimeo so I would check there if not contact the motion team.

**Comment by ccmadrid** [comment]
@paisley-laurenzio lol can you make a 1920x1080 image to be the poster for the video. Please & Thanks!

**Comment by ccmadrid** [comment]
cool so I don't think there are any more placeholders. the banner up now is going to be a carousel that will lead to the different corresponding videos, but it's not a placeholder, so I'm going to close this
