### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by natalie-macpherson** [algonquindesign-grads/2016#119]
I figured this can all go into one issue but here is what we need to check:

- [x] Content had been placed consistently 
- [x] Nav is consistently placed
- [x] shared page elements do not shift
- [x] fully responsive with nothing odd happening.(weird spacing, overlapping etc)
- [x] Typography and grid system is applied 
- [x] Consistent graphic look and feel
- [x] All page layouts have been tested.

**Comment by ccmadrid** [comment]
only thing is on the inside pages at 240px wide, some really long emails get cut off

**Comment by ccmadrid** [comment]
affects: valerie, michelle, brendan, marissa, paisley, sam, christianne, liz, chenise, mike
my solution would be to make an email icon for this tiny screen size

**Comment by ccmadrid** [comment]
@dagerebe changed it to the icon on tiny screens!
