### ISSUE TITLE
Skip links and focus styles (accessibility)

### ISSUE THREAD

**Issue by natalie-macpherson** [algonquindesign-grads/2016#123]

**Comment by natalie-macpherson** [comment]
Opening up issues again. I completely forgot about focus states on the filter. Nice catch @ccmadrid!

**Comment by ccmadrid** [comment]
@thomasjbradley is there a way for once we hit enter on a navigation focus, it changes the item thats in focus to the first link of that section? it's weird if I choose "connect" for example, it will bring me down to connect, but then if I hit tab, it will bring me back up.

**Comment by thomasjbradley** [comment]
Some Javascript + some `tabindex`:

```js
$('.fw-navigation a').on('keypress', function (e) {
  $($(this).attr('href')).focus();
});
```

Then onto each of the `<div>` tags that match the ID for the nav links add `tabindex="0"`.

**Comment by ccmadrid** [comment]
sweet I can get this to work with control+option+space, but if I use enter, its the same as before. is  control+option+space something that's more likely to be used for people who need this form of accessibility?

**Comment by thomasjbradley** [comment]
Is that with VoiceOver on?
Then, yes, that's part of VoiceOver’s system.

**Comment by ccmadrid** [comment]
no, I turned it off to test it as well

**Comment by thomasjbradley** [comment]
Huh... what browser? I tested in Firefox.

**Comment by ccmadrid** [comment]
I'm using chrome right now. so if I press enter when focused on a nav link and then press tab it brings me to the next item in the nav list

**Comment by thomasjbradley** [comment]
Is this committed to the live version so I can test?

**Comment by ccmadrid** [comment]
yes it should be

**Comment by thomasjbradley** [comment]
Just tested in Chrome and seems to work for me... let's call it good enough.
