### ISSUE TITLE
Correct elements have WAI-ARIA landmark roles (Accessibility)

### ISSUE THREAD

**Issue by natalie-macpherson** [algonquindesign-grads/2016#124]
@thomasjbradley 
do we need to include this in the website?

**Comment by thomasjbradley** [comment]
Always.

**Comment by ccmadrid** [comment]
I think I did this right.

@thomasjbradley would you consider the dropdown menu for the grad filter a "form" or even the whole filter as an "application"?

should we even touch the document structure roles and widget roles that are in the w3 documentation?

**Comment by thomasjbradley** [comment]
I don't think you need `form` or `application` on the filter, it's good enough as it is.

**Comment by thomasjbradley** [comment]
The rest of the roles look good.

**Comment by ccmadrid** [comment]
sweeeeeeeet
