### ISSUE TITLE
Tested with accessibility tool (Accessibility)

### ISSUE THREAD

**Issue by natalie-macpherson** [algonquindesign-grads/2016#126]
- [x] color oracle
- [x] keyboard only
- [x] un-clrd (black and white only) using <img width="48" alt="screen shot 2016-03-02 at 2 51 56 am" src="https://cloud.githubusercontent.com/assets/6340291/13453915/c4fc2364-e021-11e5-8299-78dff31f03dc.png">
- [x] web developer
- [x] color contrast check

**Comment by vivkay** [comment]
@natalie-macpherson all of the labels for the grad type currently fails the contrast check.
![screen shot 2016-03-01 at 9 06 45 am](https://cloud.githubusercontent.com/assets/6340292/13429202/133b08fa-df8d-11e5-9509-c98ec72cc7bb.png)

We need to change to our standard grey #55565a 
![screen shot 2016-03-01 at 9 08 31 am](https://cloud.githubusercontent.com/assets/6340292/13429223/386d34ea-df8d-11e5-9759-9138e166759a.png)

**Comment by vivkay** [comment]
I don't even need to test this one…(contrast fail)
![screen shot 2016-03-01 at 9 10 22 am](https://cloud.githubusercontent.com/assets/6340292/13429277/79af37dc-df8d-11e5-8dc1-cb8238eed277.png)

**Comment by vivkay** [comment]
Also no good:
![screen shot 2016-03-01 at 9 10 59 am](https://cloud.githubusercontent.com/assets/6340292/13429381/f6bdee08-df8d-11e5-8380-df84004a72a2.png)

![screen shot 2016-03-01 at 9 13 53 am](https://cloud.githubusercontent.com/assets/6340292/13429383/f975d354-df8d-11e5-88bb-16e0e114e6da.png)

**Comment by vivkay** [comment]
I recommend we change them to our standard grey #55565a with white.

![screen shot 2016-03-01 at 9 08 31 am](https://cloud.githubusercontent.com/assets/6340292/13429223/386d34ea-df8d-11e5-9759-9138e166759a.png)

**Comment by vivkay** [comment]
![screen shot 2016-03-01 at 9 15 58 am](https://cloud.githubusercontent.com/assets/6340292/13429437/3d73020c-df8e-11e5-9c0e-6c4a0df2103a.png)
(no good)

**Comment by vivkay** [comment]
Another contrast fail

![screen shot 2016-03-01 at 9 19 26 am](https://cloud.githubusercontent.com/assets/6340292/13429531/b7189e0a-df8e-11e5-80d9-1685bda4ca5d.png)


![screen shot 2016-03-01 at 9 19 02 am](https://cloud.githubusercontent.com/assets/6340292/13429521/ac2fd47c-df8e-11e5-95e7-0a24a6a47767.png)

**Comment by vivkay** [comment]
Recommendations / mockup:

![screen shot 2016-03-01 at 9 35 59 am](https://cloud.githubusercontent.com/assets/6340292/13429995/077f388e-df91-11e5-87ff-d30e9786efd1.png)

**Comment by vivkay** [comment]
Color oracle checks look good.
