### ISSUE TITLE
 HTML validation and indentation (Quality Control)

### ISSUE THREAD

**Issue by natalie-macpherson** [algonquindesign-grads/2016#128]
Note (we are using SCSS so we already know that css validates)

**Comment by ccmadrid** [comment]
I was able to fix most of the validation stuff. One thing that stuck out is that Sara Clayton has 2 specialties and I wrote the jekyll to have spacing between three of them, so we're getting the error that the attribute is ending in white space. I'll talk to her about just adding a third.

Not sure how to fix the rest. I had hid an H1 before but I know that's bad etiquette. but at least it validated.

file:///Users/kidmadrid/Documents/TotalValidatorTool/Results/page5283004213060270840.html

**Comment by ccmadrid** [comment]
just validated main page and both cases for inside pages. everything validates except a few of unrecognized meta tags and a missing label for the filter, empty(by choice) alt attributes for the inside pieces, and the empty instagram ul that gets filled through javascript. 

Just need to clean up indentations and looking at the index in the _site folder, it's pretty close
