### ISSUE TITLE
Tested on screens size 240px to ~2500px (Browser Testing)

### ISSUE THREAD

**Issue by natalie-macpherson** [algonquindesign-grads/2016#132]

**Comment by paisley-laurenzio** [comment]
I looked at the site on a screen size of 240 and when the navigation is opened it gets cut off. 
![screen shot 2016-03-01 at 5 01 00 pm](https://cloud.githubusercontent.com/assets/6371044/13443473/3379e9fa-dfcf-11e5-8d57-1dccac77c347.png)

**Comment by natalie-macpherson** [comment]
Additional issue on 240px screens:

<img width="102" alt="screen shot 2016-03-04 at 9 13 33 am" src="https://cloud.githubusercontent.com/assets/6340291/13529333/a8141a4e-e1e9-11e5-8c48-b4de678b4052.png">

And thoughts about this: 
![screen shot 2016-03-04 at 9 13 50 am](https://cloud.githubusercontent.com/assets/6340291/13529447/44fd9600-e1ea-11e5-9690-e0b2d5162026.jpg)

Should we drop the second number (46 minutes) to the second line next to the seconds. Make it into a square on small screens? We can leave it as it but in terms of #gravy it might look nicer and keep with the shapes outlines with the brand...Small details!

**Comment by dagerebe** [comment]
I can fix that and make it a square on smaller screens!

**Comment by ccmadrid** [comment]
sorry guys, I assumed the only thing breaking was my nav

**Comment by paisley-laurenzio** [comment]
Also I noticed on small screens we have some dropping happening. 
![screen shot 2016-03-04 at 10 07 26 am](https://cloud.githubusercontent.com/assets/6371044/13530745/ef12324e-e1f0-11e5-9574-f0cc9ebd8eda.png)
