### ISSUE TITLE
Performance budget (Performance)

### ISSUE THREAD

**Issue by natalie-macpherson** [algonquindesign-grads/2016#138]
https://developers.google.com/speed/pagespeed/insights/
https://www.google.com/webmasters/tools/mobile-friendly/
http://www.webpagetest.org/

I asked a few of my friend from many places around the world (US, Australia, Thailand, Malaysia,  Canada etc) and they all said they had issues loading things on the site. I wonder if this is because it is being hosted on github or if it is because we are using Amazon? Any idea and if there is a way to solve this.

When running it through webpagetest.org the video is a big problem with proformance. http://www.webpagetest.org/result/160228_5Z_K5C/ 

@thomasjbradley maybe you have an answer or an explanation for this because when I did user testing comments were made about the slow loading time.

**Comment by thomasjbradley** [comment]
There are a few reasons why its slow.

- 76 images are loaded on the homepage (nothing can be done about this).
- 7 JS files are loaded (should be concatenated into one as mentioned in #140).
- Yeah, every included video is hella going to slow the website. (I usually get around this by not having a video to begin with, but a static graphic, then clicking the button adds the `<video>` tag to the website.)

---

Amazon, GitHub and CloudFlare are really, really positive and only helping your website be as fast as it can be right now.

**Comment by thomasjbradley** [comment]
These images are **HUGE!!**

<img width="906" alt="screen shot 2016-03-01 at 12 34 37 pm" src="https://cloud.githubusercontent.com/assets/105192/13435816/350c4350-dfaa-11e5-969d-914841134679.png">

## 642 KB !?

**Comment by natalie-macpherson** [comment]
images have been resized and saved for web again

**Comment by ccmadrid** [comment]
@thomasjbradley is your video fix a js thing?

**Comment by thomasjbradley** [comment]
@ccmadrid Yeah, we'd display just a regular `<img>` tag on the page. When the user clicks that `<img>` we delete that tag from the HTML and insert a `<video>` tag that autoplays with JS.

**Comment by ccmadrid** [comment]
so I tried just replacing the video with an img and doing tests with webpage test. it definitely doesn't have the video loading problem, but the overall page load time is still pretty yikes. I'll try making the js built video tag anyways, but thought I'd let you guys know I tried doing tests with just the image

**Comment by ccmadrid** [comment]
hey @thomasjbradley what do you think about making smaller thumbnail versions of the grads for the front page? using the inspector I found that the largest they ever get is around 300px. so that x2 would be 600px and they're 960px right now. soon we could save a bit. worth it?

**Comment by thomasjbradley** [comment]
Yeah, that would probably make a big difference for loading the homepage, but then we'd lose the caching performance of the inside pages because they'd be using a different image.

It's probably worth it because the front page performance would be much better and the inside pages would just get a tiny bit slower, probably nobody would notice.

**Comment by ccmadrid** [comment]
ok great. ya on the inside pages, the biggest they get is around 600px, so the 960px is still necessary I guess?

**Comment by ccmadrid** [comment]
I made 640px wide versions, and they seem to help a bit. cut the full page load time by 4 seconds (15ish to 11ish); I could just be placebo-ing myself, but I feel that the page paint times are better, and the hover stuff is smoother. closing
