### ISSUE TITLE
Remove Redundant HTML/SCSS/JS (Performance)

### ISSUE THREAD

**Issue by natalie-macpherson** [algonquindesign-grads/2016#139]
- filter.js needs to be removed or fixed (webpagetest.org loads the file multiple times)

**Comment by natalie-macpherson** [comment]
Redundant HTML and SCSS has been removed

**Comment by ccmadrid** [comment]
great. other than the video webpagetest looks pretty decent. good job everyone! i still think the css needs  to be combed through to see if there are unused styles, and elements combed through to see if there are unused classes.

**Comment by ccmadrid** [comment]
I used the inspector's audit feature to find out what classes aren't being used. it's saying 64% of the rules in our style.css are not being used (mainly from the grid and typography libraries) I'm closing this for now, but if you guys think going through and only keeping the ones we use would help, then we can reopen this
<img width="387" alt="screen shot 2016-03-08 at 6 51 45 am" src="https://cloud.githubusercontent.com/assets/6340290/13600940/5496cd8a-e4fa-11e5-8302-27e97f9fa5cf.png">
