### ISSUE TITLE
Javascript needs to be concatenated and minified

### ISSUE THREAD

**Issue by natalie-macpherson** [algonquindesign-grads/2016#140]

**Comment by natalie-macpherson** [comment]
@thomasjbradley It has occurred to me that I am not quite sure how to do this when using SCSS? Can you point me in the right direction. Also for the js would it be better to just put all the js in a single file so we don't have to download multiple files? Did we learn how to minify js? I can't seem to find it in the tutorials...

**Comment by thomasjbradley** [comment]
I believe you're all using Prepros, right?

If I understand correctly it can do all those things for you... you'll just have to look through it because I don't know how to do it with Prepros.

**Comment by natalie-macpherson** [comment]
Ok I'll take a look at it.  I know the area where the minifying is in I just have no idea what option to click.

![screen shot 2016-03-02 at 11 26 16 am]
(https://cloud.githubusercontent.com/assets/6340291/13466823/a1eb0564-e069-11e5-8bc8-dd90108c3476.png)

![screen shot 2016-03-02 at 11 26 24 am](https://cloud.githubusercontent.com/assets/6340291/13466828/a614d764-e069-11e5-8214-e4d3b3a844c0.png)


Also, I'm still wondering if we should just make 1 js file with all the js in it instead of multiple one?

**Comment by thomasjbradley** [comment]
I think those options are okay.

For minifying the CSS, you need to select the `style.scss` file and switch to compressed.

<img width="1112" alt="screen shot 2016-03-02 at 11 43 30 am" src="https://cloud.githubusercontent.com/assets/105192/13467427/37b0df36-e06c-11e5-92c4-11120d545127.png">

Here's a tutorial to get Prepros to automatically combine the JS files together.
https://prepros.io/docs/concatenate-and-minify-javascript

I'd make a new file called `main.js` that uses those fancy comments to import all the other JS files.
Then in the `default.html` layout, we only reference `main.js` not the individual files.

**Comment by natalie-macpherson** [comment]
@ccmadrid the .js and .css files have been minified but the js for the navigation, waypoint, instagram are not working when we call upon the main-dist.js file. I would take a look at it. The clock and filter work fine. I have commented out the js. files but they are still in the default.html.

**Comment by thomasjbradley** [comment]
@natalie-macpherson Double check that the JS files in `main.js` are in the same order they were in `default.html`.

**Comment by natalie-macpherson** [comment]
@thomasjbradley They are the same on both the `main.js` and `default.html`

**Comment by ccmadrid** [comment]
the problem was in vivs js that was called first & the filter doesn't use js anyways so that should always work. there was an unused function in the clock js that was looking for something that didn't exist. since Natalie combined them that put a halt on the rest of the javascript. There was nothing wrong with my stuff hehehe nice try though Natalie.

**Comment by natalie-macpherson** [comment]
I'm glad you were able to solve the issue. Good work.
