### ISSUE TITLE
Checklist for in class User testing

### ISSUE THREAD

**Issue by natalie-macpherson** [algonquindesign-grads/2016#143]
The following is what we need for user testing that the web team will be conducting on Tuesday 

- Have students find their image on the landing page and check their portfolio page to make sure everything they want there is there. Have them check it on desktop and on mobile since the content/layout is different for both.

- Check that their name is correct on the homepage and the inside page.

- Click the filters they personally chose and make sure they're highlighted.

- Have students click on links throughout the page to make sure they are all working. 
    - Click their domain
    - Click their email address, and send a message to themselves—and make sure they receive it
    - Click all 3 of their social links
    - If they included a video, play it to make sure its the correct one

- Have students check the website on their phones/tablet etc to see if there are any issues with overlapping/missing content etc....

- Have student try the website on different browsers.

**All issues they find ask the students to submit issues to Github which will resolved after class.**

**Comment by thomasjbradley** [comment]
I’m just going to edit your issue a little...
