### ISSUE TITLE
Filter break

### ISSUE THREAD

**Issue by vivkay** [algonquindesign-grads/2016#146]
Hi @thomasjbradley,

I'm trying to find a solution so that we never have one filter button hanging lonely on it's own. 

This is ok:

![screen shot 2016-02-28 at 1 11 33 pm](https://cloud.githubusercontent.com/assets/6340292/13380957/25280016-de1d-11e5-83d9-56c3daa7e40e.png)

But this is sad news salmon: 
![screen shot 2016-02-28 at 1 11 39 pm](https://cloud.githubusercontent.com/assets/6340292/13380960/2a721020-de1d-11e5-9f9f-16c582b153fc.png)

I tried to wrap the two last inputs in a div, and make that div display block at a certain media query, but that didn't seem to do much. 

```
<input class="filter-radio" id="filter-all" checked type="radio" name="filters">
<input class="filter-radio" id="filter-branding" type="radio" name="filters">
<input class="filter-radio" id="filter-ux" type="radio" name="filters">
<input class="filter-radio" id="filter-web" type="radio" name="filters">
<input class="filter-radio" id="filter-illustration" type="radio" name="filters">
<input class="filter-radio" id="filter-motion" type="radio" name="filters">
<input class="filter-radio" id="filter-print" type="radio" name="filters">
<div class="filter-no-break">
  <input class="filter-radio" id="filter-type" type="radio" name="filters">
  <input class="filter-radio" id="filter-photo" type="radio" name="filters">
</div>

```

```
@media only screen and (min-width: 38em) {
.filter-no-break {
  display: block;
}
```

Any ideas? I basically want a $nbsp; between those last two inputs... (I also tried that, JUST IN CASE). No dice. :game_die: 

Thanks!

**Comment by thomasjbradley** [comment]
The `<div>` solution is really close. You just need to change the CSS a little.

```css
.filter-no-break {
  display: inline-block;
  white-space: nowrap;
}
```

And remove it from the media query.

**Comment by vivkay** [comment]
Hi @thomasjbradley,

This doesn't seem to be working. I did some more inspecting and found that the .filter-no-break div was connecting, but it had dimensions of 0x0 and appears higher on the browser (see screenshot). 

I tried a few more things, but nothing made any affect. Even adding a background colour etc. didn't change anything. 

```
.filter-no-break {
  display: inline-block;
  white-space: nowrap;
  float: left;
  width: 3em;
  background-color: red;
  color: green;
  position: absolute;
}
```

More inspecting showed that the individual buttons are displaying because of the .filter-btn class which is only called from js. 

![screen shot 2016-03-01 at 8 26 46 am](https://cloud.githubusercontent.com/assets/6340292/13428525/07787772-df89-11e5-8299-e9bae6c361d5.png)
![screen shot 2016-03-01 at 8 32 48 am](https://cloud.githubusercontent.com/assets/6340292/13428531/0bc60114-df89-11e5-899a-f08ef8242db1.png)

I assume it's only called from .js because this is the html:
```
<input class="filter-radio" id="filter-all" checked type="radio" name="filters">
<input class="filter-radio" id="filter-branding" type="radio" name="filters">
<input class="filter-radio" id="filter-ux" type="radio" name="filters">
<input class="filter-radio" id="filter-web" type="radio" name="filters">
<input class="filter-radio" id="filter-illustration" type="radio" name="filters">
<input class="filter-radio" id="filter-motion" type="radio" name="filters">
<input class="filter-radio" id="filter-print" type="radio" name="filters">
<div class="filter-no-break">
  <input class="filter-radio" id="filter-type" type="radio" name="filters">
  <input class="filter-radio" id="filter-photo" type="radio" name="filters">
</div>
```

and this is the js
```
var $filterSelect = $('#filter-select');
var $filterBtn = $('.filter-btn');

$filterSelect.on('change', function () {
  $('[for="' + $(this).val() + '"]').click();
});

$filterBtn.on('click', function () {
  $filterSelect.val($(this).attr('for'));
});
```

Because the label .filter-btn seems to e directly affecting the buttons, but isn't in the html, I tried to call it with the nth child (still didn't work). 

```
.filter-btn:nth-child(9n) {
  color: blue;
  display: inline;
}

.filter-btn:nth-child(10n) {
  display: inline;
}
```
Any other ideas of how to keep these two last elements together?

Thanks!

**Comment by vivkay** [comment]
It's ok, Christian figured out a different solution!

**Comment by thomasjbradley** [comment]
That seems like a lot of trouble.
I downloaded the website and wrote that code in it and it worked properly... oh well.
