### ISSUE TITLE
Videos on homepage

### ISSUE THREAD

**Issue by natalie-macpherson** [algonquindesign-grads/2016#165]
The videos on the homepages are the same. We need to change them so the billboard one is different from the behind the scene video. Somebody will have to contact the Motion team to see what the ETA is on their video so we can add them to the site.

If you wish you take this job assign yourself this task

**Comment by ccmadrid** [comment]
I changed the video in my branch and it'll update when its merged, but we still need t get the actual videos for both the behind the scenes stuff and the hero video

**Comment by natalie-macpherson** [comment]
please refer to issue #114. I am closing this issue.
