### ISSUE TITLE
Uneven spacing around grad links

### ISSUE THREAD

**Issue by thomasjbradley** [algonquindesign-grads/2016#170]
I don't think the spacing should be different in these two places:

![screen shot 2016-03-01 at 7 01 34 am](https://cloud.githubusercontent.com/assets/105192/13426713/4944899a-df7d-11e5-84ab-17b3343f4864.png)

**Comment by annamisak** [comment]
I will remove the extra space.

**Comment by annamisak** [comment]
Fixed
