### ISSUE TITLE
Intro blurb text too small

### ISSUE THREAD

**Issue by thomasjbradley** [algonquindesign-grads/2016#173]
Is this text for ants to read?

![screen shot 2016-03-01 at 7 02 08 am](https://cloud.githubusercontent.com/assets/105192/13426782/b0cf59be-df7d-11e5-80c1-c0456d9dacc9.png)

**Comment by ccmadrid** [comment]
was that a zoolander reference? +500 Christian points
Can we also rewrite the blurb guys? get branding to write something a little more on brand and discuss the theme a bit?

**Comment by natalie-macpherson** [comment]
The font is larger. If we want to get branding to write something else we can replace what we have.
