### ISSUE TITLE
Responsive issues

### ISSUE THREAD

**Issue by thomasjbradley** [algonquindesign-grads/2016#185]
On medium & small screens:

<img width="429" alt="screen shot 2016-03-01 at 12 13 54 pm" src="https://cloud.githubusercontent.com/assets/105192/13435290/8f1d53b4-dfa7-11e5-93b5-6e5f37716db1.png">

The event title overlaps the image.

---

On small screens:

<img width="240" alt="screen shot 2016-03-01 at 12 14 14 pm" src="https://cloud.githubusercontent.com/assets/105192/13435294/93670438-dfa7-11e5-900d-5a1ff6ba91d8.png">

Add more space after the “Google Calendar” link.

**Comment by elisak** [comment]
Watch all button, on small screen
![screen shot 2016-03-01 at 1 50 55 pm](https://cloud.githubusercontent.com/assets/6330212/13437938/b315f700-dfb4-11e5-867e-f578e64bbf10.png)

**Comment by elisak** [comment]
Ticket bottom may need to be styled, it's not aligned/ feels off
![screen shot 2016-03-01 at 1 57 07 pm](https://cloud.githubusercontent.com/assets/6330212/13438123/9eaa4ed2-dfb5-11e5-9d56-de4446a879ab.png)

**Comment by natalie-macpherson** [comment]
Responsive issues fixed
