### ISSUE TITLE
Tickets button

### ISSUE THREAD

**Issue by thomasjbradley** [algonquindesign-grads/2016#186]
It doesn’t go anywhere! (On medium/small screens.) Also isn’t an `<a>` tag.

<img width="390" alt="screen shot 2016-03-01 at 12 13 30 pm" src="https://cloud.githubusercontent.com/assets/105192/13435358/e7a042d0-dfa7-11e5-88b6-c83bcdffe092.png">

---

How do I get to the tickets thing here?
I had to ask Natalie because my brain completely ignored the Eventbrite icon—I thought it was some garbage social media icon.

<img width="928" alt="screen shot 2016-03-01 at 12 22 28 pm" src="https://cloud.githubusercontent.com/assets/105192/13435440/5fcc3bd8-dfa8-11e5-8d78-9c5402e99e31.png">

**Comment by vivkay** [comment]
- ticket link now in sidebar or middle bar (Contrast updated)
-social links removed (Rebecca)
- countdown timer now on right hand side (Rebecca added)

**Comment by natalie-macpherson** [comment]
The button to get ticket should still be in the about section. Maybe including it under countdown times
