### ISSUE TITLE
Favicon is blurry on retina displays

### ISSUE THREAD

**Issue by thomasjbradley** [algonquindesign-grads/2016#188]
<img width="212" alt="screen shot 2016-03-01 at 12 37 56 pm" src="https://cloud.githubusercontent.com/assets/105192/13435874/768b88c2-dfaa-11e5-9346-243689775af4.png">

Needs to be an `.ico` file with both `16px` and `32px` sizes inside.
Generate the file here: http://www.xiconeditor.com/

**Comment by paisley-laurenzio** [comment]
I updated the favicon to an ico file on amazon.
