### ISSUE TITLE
Banner Image

### ISSUE THREAD

**Issue by jesspaget** [algonquindesign-grads/2016#194]
Banner image spacing looks a little awkward. Once the video plays it looks great - it's just the banner image top & bottom spacing. 
<img width="1408" alt="screen shot 2016-03-01 at 12 57 00 pm" src="https://cloud.githubusercontent.com/assets/6373211/13436406/1e267176-dfad-11e5-81fb-9f5bfce30583.png">

**Comment by dagerebe** [comment]
Is there a way that we can use a frame of the video as the banner ?

**Comment by natalie-macpherson** [comment]
The image is currently a placeholder and will be replaced when we receive another image. If you want to see what the billboard will look like at the end of the day click on the play button. The video is the size of the billboard.

**Comment by ccmadrid** [comment]
we can definitely use a frame of the video for the banner, but this isn't the correct video. we need to bug motion to get both this hero video and the behind the scenes playlist

**Comment by natalie-macpherson** [comment]
I am going to close this issues and make reference to it in issues #196. They are very similar is context.
