### ISSUE TITLE
Home page: issues with billboard

### ISSUE THREAD

**Issue by Mike-Slingerland** [algonquindesign-grads/2016#196]
I opened the grad site on my phone and the main video on the home page works, but the pause button stays visible through the whole clip.

**Originally from issue #194**
Banner image spacing looks a little awkward. Once the video plays it looks great - it's just the banner image top & bottom spacing. 
<img width="1408" alt="screen shot 2016-03-01 at 12 57 00 pm" src="https://cloud.githubusercontent.com/assets/6373211/13436406/1e267176-dfad-11e5-81fb-9f5bfce30583.png">

**Comment by ccmadrid** [comment]
changed to the newish billboard. closing this for now. I'll work on making the new one snazzy tonight
