### ISSUE TITLE
"É" is larger than other letters

### ISSUE THREAD

**Issue by kayleemenard** [algonquindesign-grads/2016#198]
On my portfolio page, the "É" is larger than the other letters of my name.

(It doesn't bother me, but it is visible)

And on smaller screen sizes, my name overlaps:
<img width="235" alt="screen shot 2016-03-01 at 1 00 17 pm" src="https://cloud.githubusercontent.com/assets/6373202/13436521/a05ffd7e-dfad-11e5-9277-426806705d06.png">

**Comment by thomasjbradley** [comment]
Turned on French accents... hopefully fixes it.

**Comment by annamisak** [comment]
I think it also might be the line-height needs to be adjusted as well.
