### ISSUE TITLE
Safari - framework logo not in proper place

### ISSUE THREAD

**Issue by heathermcd12** [algonquindesign-grads/2016#199]
<img width="1405" alt="screen shot 2016-03-01 at 12 53 06 pm" src="https://cloud.githubusercontent.com/assets/6333582/13436462/5b956b52-dfad-11e5-9040-e7d64db61b6d.png">

**Comment by paisley-laurenzio** [comment]
Several of us checked the site in safari and none of us had the same issue with the miss placed logo. Everything seems to be working now!

**Comment by thomasjbradley** [comment]
@heathermcd12 What version of Safari are you using?
@paisley-laurenzio What version are you using?

**Comment by paisley-laurenzio** [comment]
@thomasjbradley I'm using version 9.
