### ISSUE TITLE
return filename without extension

### ISSUE THREAD

**Issue by ccmadrid** [algonquindesign-grads/2016#23]
@thomasjbradley 
so I found the {{something.path}} stuff for jekylll to match up the md filenames to the photos on the amazon server, but I can't figure out how to get rid of the extension. Help please!

**Comment by thomasjbradley** [comment]
I would probably do something like this:

```
{{something.path | replace: '.md', ''}}
```

**Comment by ccmadrid** [comment]
ou k I just came up with something tricky hehe I used{{something.url}} and put the pictures in a grads folder too to match. but this was seems much more legit. Thanks!

**Comment by ccmadrid** [comment]
ou sorry. it gives the whole path like starting from my /user through all the folders to get to it

**Comment by thomasjbradley** [comment]
Can I see in your code where you're using it?

**Comment by thomasjbradley** [comment]
In the loop for the collection?

**Comment by ccmadrid** [comment]
`<section class="ph-graduates">
	<ul class="filter-items ph-student">
  {% for student in site.grads %}
      <li class="ph-student" data-category="{% for a in student.specialization%}{{a}} {% endfor %}">
        <a href="#">
        <img class="img-flex ph-gradphoto-top" src="http://grads.images.algonquindesign.ca.s3.amazonaws.com/2016/portraits{{student.path | pretty replace '.md','' }}" alt="{{student.full_name}}">
        <p class="ph-fullname">{{student.full_name}}</p>
        <p class="ph-partialname">{{student.short_name}}</p>
        </a>
      </li>
  {% endfor %}
</ul>
</section>`

**Comment by thomasjbradley** [comment]
What about `student.name` — `name` is part of the Jekyll collection system.

**Comment by thomasjbradley** [comment]
Also, you can change the URL for S3, `http://grads.images.algonquindesign.ca.s3.amazonaws.com/2016` to this:

```
{{site.cdn}}
```

It's configured in the `_config.yml` file.

**Comment by ccmadrid** [comment]
ok cool I'll try those

**Comment by ccmadrid** [comment]
is what I said earlier too iffy? because it seemed to work alright. I'll just need to add a grads folder to match

**Comment by ccmadrid** [comment]
nvm I think I got it!

**Comment by ccmadrid** [comment]
`{{site.cdn}}/portraits{{student.url | replace: 'grads/', ''}}`

thanks! I'm getting a bunch of 403s though

**Comment by thomasjbradley** [comment]
What does the final URL look like when you inspect it in the browser?

**Comment by ccmadrid** [comment]
lame, i need the .jpg at the end. The thing is that it gives a"/" at the end before I can put the extension

**Comment by thomasjbradley** [comment]
`replace: '/grads/', ''`

**Comment by ccmadrid** [comment]
the / is still before the .jpg. hmm

**Comment by thomasjbradley** [comment]
Send me your Jekyll code and what the URL looks like in the browser.

**Comment by ccmadrid** [comment]
`"{{site.cdn}}/portraits/{{student.url | replace: 'grads/', '/' | remove:'/'}}.jpg"`
got it!

**Comment by thomasjbradley** [comment]
Super!

**Comment by ccmadrid** [comment]
but now its sending the 403s I'll check the link in the config?

**Comment by ccmadrid** [comment]
ooooh nvm. they photos don't exist

**Comment by ccmadrid** [comment]
I'll wait for everyone to get their crap together.
