### ISSUE TITLE
Missing Unit? (Back to top) 

### ISSUE THREAD

**Issue by sky-bones** [algonquindesign-grads/2016#246]
Might be a glitch situation, but the 'back to top' did this: 

<img width="204" alt="screen shot 2016-03-01 at 8 41 17 pm" src="https://cloud.githubusercontent.com/assets/6333963/13448062/11fd05f4-dfee-11e5-9e47-92a496abfd38.png">

It also fully disappears at one point (intentional?)  

This happened on my profile page (using chrome,  latest version on my laptop)

**Comment by natalie-macpherson** [comment]
Ah we were working on the code and things collapsed it's all good now :) thanks for the heads up!
