### ISSUE TITLE
Thomas's what if list

### ISSUE THREAD

**Issue by natalie-macpherson** [algonquindesign-grads/2016#256]
- [x] What if the images don’t download or aren’t visible?
- [x] What if the images are black & white?
- [x]  What if the font-size is significantly larger? Or smaller?
- [x]  What if CSS is disabled or doesn’t load?
- [x]  What if the browser doesn’t support newer CSS features?
- [x]  What if the browser doesn’t support newer HTML features?
- [x]  What if they’re using a text-only browser?
- [ ]  What if the browser is smaller? Or bigger?
- [x]  What if they’re using only a keyboard?
- [x]  What if they’re using a touch device?
- [x]  What if Javascript is disabled?
- [x]  What if there’s a Javascript error and it doesn’t run?
- [x]  What if the Internet connection is slow?
- [x]  What if the user prints out the website?
- [x]  What if your user isn’t giving their full attention?
- [x]  What if there is double the amount of content on the page?
- [x]  What if your content is consumed on another website?

**Comment by ccmadrid** [comment]
I think I fixed the smaller/bigger screen issues. close if it pleases you

**Comment by natalie-macpherson** [comment]
I will close this for now. Please refer to issue #132
