### ISSUE TITLE
Filtered images on hover

### ISSUE THREAD

**Issue by natalie-macpherson** [algonquindesign-grads/2016#271]
I remember talking to @ccmadrid about not having the images transition on a hover if they are filtered out. Are we still doing this?

**Comment by ccmadrid** [comment]
Yes I'll work on that tonight


On Mar 2, 2016, at 14:18, natalie-macpherson <notifications@github.com<mailto:notifications@github.com>> wrote:


I remember talking to @ccmadrid<https://github.com/ccmadrid> about not having the images transition on a hover if they are filtered out. Are we still doing this?

-
