### ISSUE TITLE
Side bar 

### ISSUE THREAD

**Issue by gumbey** [algonquindesign-grads/2016#275]
I don't know if this is already a issue but,

When full screen on my laptop
-nav buttons have a scroll bar
-Framework is cut off

Image for the visual people.
<img width="849" alt="screen shot 2016-03-03 at 10 08 18 am" src="https://cloud.githubusercontent.com/assets/4565418/13499478/9ef5cb14-e12c-11e5-94bf-741f69fab599.png">

**Comment by natalie-macpherson** [comment]
This is happening because we have disabile js. its fine. Thanks for the heads up!
