### ISSUE TITLE
Hover state on graph photos on load

### ISSUE THREAD

**Issue by natalie-macpherson** [algonquindesign-grads/2016#279]
Tiffany mentioned and showed me today that the hover state for the grad photos on load are really lagging...have no idea why. It only happens in Chrome.

@thomasjbradley do you know why?

**Comment by thomasjbradley** [comment]
It looks like its just because there are so many photos being loaded... at least if I'm seeing the problem you're mentioning.

**Comment by ccmadrid** [comment]
when I spoke to her she brought up page-paint times. I did update the styling or the grad photos, so we should run it through tests again.

**Comment by ccmadrid** [comment]
I think that having the smaller portraits helped with the page paint times. we could push it and go smaller to like 500px and probably save a handful of percents. I think this has been kind of resolved. closing
