### ISSUE TITLE
Return To Top Button Text Overlap

### ISSUE THREAD

**Issue by paisley-laurenzio** [algonquindesign-grads/2016#287]
I noticed that on all screen sizes the Return To Top button gets smushed and the text overlaps itself when you are viewing the individual portfolio pages. On the home page it is fine though. 

![screen shot 2016-03-04 at 10 19 31 am](https://cloud.githubusercontent.com/assets/6371044/13531072/9bf0c29a-e1f2-11e5-984b-d2186bb839be.png)

**Comment by ccmadrid** [comment]
ou should I just disable it for the inside pages? there isn't enough content to justify having it. agree disagree?

**Comment by natalie-macpherson** [comment]
@dagerebe and I think we should disable it on the inside pages because it is not long enough to warrant it.
