### ISSUE TITLE
Issue with nav on inside page for chrome on PC

### ISSUE THREAD

**Issue by natalie-macpherson** [algonquindesign-grads/2016#289]
![inside-nav issue](https://cloud.githubusercontent.com/assets/6340291/13541786/77d46166-e22c-11e5-98a6-cefd2b6f0a87.jpg)

Not sure how we can fix and test this because it works fine on our macs. 

Note: My chrome I believe is up to date.

**Comment by ccmadrid** [comment]
probably just forcing an overflow: visible on the nav element. Does this happen for the other screen sizes? can you do that in the inspector and see if that fixes it? pls and thanks

**Comment by natalie-macpherson** [comment]
Overflow:visible fixes the issue. The issue only happens on large screen when the nav in on the side.
