### ISSUE TITLE
Blurb disappear in small screen view

### ISSUE THREAD

**Issue by annamisak** [algonquindesign-grads/2016#291]
The club section no longer available when the screen is less 480px wide. 

<img width="531" alt="screen shot 2016-03-04 at 10 25 35 pm" src="https://cloud.githubusercontent.com/assets/6360209/13545398/2cb55b8c-e258-11e5-888d-92471d00cc37.png">

**Comment by natalie-macpherson** [comment]
In the design for the wireframe on small screens the about info disappears. .

**Comment by ccmadrid** [comment]
I just left the blurb section in. it also makes sure the layout for the countdown doesn't break. I'll add a no script styling for the countdown too so that if there's not js it won't look blank with the day/hr/min/s headings
