### ISSUE TITLE
can't focus on filter buttons

### ISSUE THREAD

**Issue by ccmadrid** [algonquindesign-grads/2016#298]
@thomasjbradley is there a way to focus on the filter buttons? I'm starting to add focus states for accessibility and I can't tab onto the filter

**Comment by thomasjbradley** [comment]
You can try adding `tabindex="0"` to each of the labels... that should do it.

**Comment by ccmadrid** [comment]
ok I'll try that thanks

**Comment by ccmadrid** [comment]
@thomasjbradley ok I can focus on them but I can't press space or enter to make use of them

**Comment by thomasjbradley** [comment]
A little bit of Javascript helps out:

```js
$('.filter-btn').on('keypress', function (e) {
  $(this).click();
});
```
