### ISSUE TITLE
Sponsor logos

### ISSUE THREAD

**Issue by ccmadrid** [algonquindesign-grads/2016#323]
Here is a list of companies that I think donated to our silent auction. It would be nice to have logos made for our sponsor section made just in case we do clarify that they're a sponsor
- [ ] The Grand
- [ ] Doree's Habit
- [ ] Metropolitan
- [x] Nspired
- [ ] Algonquin Dental
- [ ] Connections Bookstore
- [ ] Off The Dome (lol)
- [x] Subway
- [ ] Kungfu Bistro
- [x] Algonquin SA

This should definitely be finalized before Tuesday's Launch

**Comment by vivkay** [comment]
Following up with some of these now - will update on progress this morning.

**Comment by ccmadrid** [comment]
o ya I don't know who the other sponsors are. I think the Kate Spade thing was from a student. I didn't get much info as to what was donated by people and what was donated by a sponsor. I'll try to find out more

**Comment by vivkay** [comment]
Re-styled logos with text only to avoid issues collecting logos (time constraints) and for greater aesthetic control and accessibility-friendliness. :baby_chick:
