### ISSUE TITLE
Rewrite Blurb

### ISSUE THREAD

**Issue by ccmadrid** [algonquindesign-grads/2016#324]
I've mentioned this to a few people, but I feel that the tone of the blurb is a little too casual, and the "bring forth" makes it feel a little cheesy/fake. Also, not enough background for the theme is mentioned, which is unfortunate because there's so much that can be said that would clarify design elements in the website, and encourage the viewer to browse the whole site. There's a call to action but no real welcome message (UX!)

**Comment by vivkay** [comment]
I'll chat with Branding about the wording for the theme and re-write something this morning. *in progress*

**Comment by vivkay** [comment]
Copy re-written, approved by Brendan (branding rep), shared on FB for team comments, and re-worked with @ccmadrid
