### ISSUE TITLE
Eventbrite Page

### ISSUE THREAD

**Issue by ccmadrid** [algonquindesign-grads/2016#325]
We have links to the Eventbrite page, but the actual Eventbrite event page is lacking. we can assume that once we launch on tuesday, people might start booking tickets, so this is an opportunity to carry our brand through more than just our site. We need to be prepared to create two classes of free tickets, (family/friends & industry) with different times associated with them so we can get an idea of how many people are coming, and when. Whoever tackles this should be in communication with Branding and the Event person(Charlie or Anna? I don't know who this is tbh)

**Comment by ccmadrid** [comment]
I have the login info for whoever wants to tackle, this. I think I have to send it over a private message on Facebook or text or in person. unless here is ok @thomasjbradley

**Comment by thomasjbradley** [comment]
No, please don’t post it here—it'll be completely open to the whole Internet.

**Comment by vivkay** [comment]
Syd S. (Brand lead) and I are on this today. :penguin:

**Comment by vivkay** [comment]
wait…two classes of tickets...hmmm. Looking at it.
