### ISSUE TITLE
Secret Prof's Page

### ISSUE THREAD

**Issue by ccmadrid** [algonquindesign-grads/2016#326]
I plan to work on this while we're out on coop, and merge it maybe after the grad show is over? whoever wants in, please help me! When it's ready to add onto the site, we can close this issue. or if we decide to scrap the idea

some things to consider:
- [ ] find out how to create a secret entryway into the teachers page that we would instruct the profs how to get to (js long press using js timers/ specific keystroke/ hidden unexpected link, etc)
- [ ] find out how to enable a comment-like system for students to get into the page and post "comments" (will act like signing the yearbook). maybe use a google form to get the messages so things can be screened and given a deadline
- [ ] need to get photos of the profs that we missed during the photoshoot days (ex, rob, angie, ...renaud?)

**Comment by vivkay** [comment]
I'll help out with this @ccmadrid

**Comment by ccmadrid** [comment]
sweeeeeet

@paisley-laurenzio Shopify squad project?

**Comment by paisley-laurenzio** [comment]
Coolio!
