### ISSUE TITLE
Previous and next buttons

### ISSUE THREAD

**Issue by ccmadrid** [algonquindesign-grads/2016#45]
We want the previous and next buttons to switch to adjacent students. if possible, we want to wrap around from the first student to the last student. This would be the tricky part I'm thinking.
If you want to tackle this and can assign yourself to this, please do.

**Comment by annamisak** [comment]
I will give it a try to make the buttons work. If I get stuck I might ask for help

**Comment by ccmadrid** [comment]
@thomasjbradley the thing I added works locally but not on gh-pages. it omits the /2016/ part of the url and I can't find out why. Is there a better way to do this?
```
{% capture grads %}{{page.collection}}{% endcapture %}
  {% if page.collection %}
    {% assign document = site[grads]  %}
  {% endif %}
{% for links in document  %}
  {% if links.title == page.title %}
    {% unless forloop.first %}
      {% assign prevurl = prev.url %}
    {% endunless %}
    {% unless forloop.last %}
      {% assign next = document[forloop.index] %}
      {% assign nexturl = next.url %}
    {% endunless %}
  {% endif %}
  {% assign prev = links %}
{% endfor %}
```
this lets me use {{prevurl}} and {{nexturl}} as the links locally

I used `| prepend: '2016'` on the assign nexturl and assign prevurl to fix that for gh-pages, but then it won't work locally

**Comment by thomasjbradley** [comment]
What about putting `{{site.baseurl}}` at the front of the `href=""`?

**Comment by ccmadrid** [comment]
nvm got it sorry I used {{base}}{{prevurl}} because I set up a base thing. site.baseurl would return the current portfolio page for some reason. it works now though!!!
