### ISSUE TITLE
style grads filter

### ISSUE THREAD

**Issue by ccmadrid** [algonquindesign-grads/2016#46]
I cannot figure out how to position the grad filter. Can we also create a dropdown for it for small screens as per the prototype? Or do we think this is an unnecessary step? it would look nice on iOS with their native styling for dropdown menus.

 If you want to tackle this and can assign yourself to this, please do.

**Comment by natalie-macpherson** [comment]
Thomas has changed the filter to make it mobile friendly. We just need to style it.

**Comment by vivkay** [comment]
I'm all over this guys. -assignedself

**Comment by vivkay** [comment]
Note for drop-down (from Thomas): Don't style it. It's a default control and is usable by people because it's recognizable. It's also a common pattern to use a default <select> box for navigation and filters on small screens.
