### ISSUE TITLE
Inside pages sprites

### ISSUE THREAD

**Issue by ccmadrid** [algonquindesign-grads/2016#48]
since we already have the sprites on the server, let's use them instead of lastname-firstname-p1, so we don't have to upload more pictures in the server. performance wise I'm thinking this would be better too if the pictures cache(if that's even how websites work); we can implement the same hover feature.
If you want to tackle this and can assign yourself to this, please do.

**Comment by annamisak** [comment]
I will work on this and replace the portfolio image to sprite.

**Comment by thomasjbradley** [comment]
You’re right @ccmadrid about caching—that's a really good idea.
