### ISSUE TITLE
logo - glow animation #gravy

### ISSUE THREAD

**Issue by ccmadrid** [algonquindesign-grads/2016#49]
the following is #gravy

currently the logo "F" changes to a lighter grey on hover. It would be cool to create an animation that cycles through the brand colours so they can appear more throughout the site.

tips: the svgs are style using fills not background-colours and safari may not transition them as nice as chrome and firefox(so don't fret)

 If you want to tackle this and can assign yourself to this, please do.

**Comment by natalie-macpherson** [comment]
I made 1 change to the animation which would add a little colour to the logo in the nav. I added the yellow in the non hover state. I would wondering, maybe we can have the transition happen without the hover and just constantly go through the colours. I want people to see this touch but people will not intuitively know to just hover and not just click on the logo to see the colours. Yes, for some people who notices the effect they might stay a few more seconds but most people will just click it.

**Comment by ccmadrid** [comment]
ok sure. @thomasjbradley any idea why the hover animation doesn't happen on the home page on hover anymore? Seems like they should both work the same because they're just in the default layout which both pages are using.

**Comment by thomasjbradley** [comment]
Which animation isn't working on hover? I can see the colours cycling through.

**Comment by ccmadrid** [comment]
this is happening for me in safari, but works fin in the inside pages

**Comment by thomasjbradley** [comment]
I don't know if this is the cause, because it doesn't make sense that it would work on the inside pages...

<img width="298" alt="screen shot 2016-02-29 at 11 55 57 am" src="https://cloud.githubusercontent.com/assets/105192/13401762/752e36b6-dedb-11e5-8ef6-e013973b0b6b.png">

The two selectors are different, I think maybe the second one is more powerful.

```css
.fw-header .logo .fw-logo:hover .svg-top {}
.fw-header .logo .fw-logo:hover svg .svg-top {}
```

Notice how the second one has `svg` in it, but the first doesn’t.

**Comment by thomasjbradley** [comment]
This now kinda flashes because the first colour in the animation is yellow but the logo starts at turquoise.

**Comment by ccmadrid** [comment]
I changed the animation to start at the current theme colour to prevent the flash

**Comment by natalie-macpherson** [comment]
Nice change it looks a lot better and not as distracting.
