### ISSUE TITLE
Framework button to make website into a wireframe/sketch - #gravy

### ISSUE THREAD

**Issue by ccmadrid** [algonquindesign-grads/2016#52]
the following is just #gravy

if you remember the initial pitch of having a button that changes the styling of stuff to make them look like wireframe/sketches? that's what this is

**Comment by natalie-macpherson** [comment]
I don't think we are going to do this one with the time we have remaining. @ccmadrid If you feel you have time at the very end you are more then welcome to take this one on. In the meantime I am closing this issue.
