### ISSUE TITLE
Change naming of inside pages layout

### ISSUE THREAD

**Issue by ccmadrid** [algonquindesign-grads/2016#55]
right now it's "portfolio-pictures". it's really nit-picky, but I'd like to change it to just "portfolio" and use the if statements to check for video so we only have to worry about one layout.

tips: this means we have to change the layout item in all of the md files.
this can be the last thing to do, or something we can do if someone is still going through all of the md files to remove the comments and corrections

**Comment by annamisak** [comment]
If we can make it work using one template for two different inside page, then we should go for it. 

I can also make the changes to the md files when needed.

**Comment by annamisak** [comment]
"portfolio-pictures.html" has been renamed to profile. All the md files has been modified to reflect the change.

Next step: Now my current focus is on connecting the video with the inside page.

**Comment by ccmadrid** [comment]
sweet
