### ISSUE TITLE
instagram live feed

### ISSUE THREAD

**Issue by ccmadrid** [algonquindesign-grads/2016#57]
It would be great to have the social med buckets auto-update to our instagram account.
I found this: https://github.com/stevenschobert/instafeed.js
which could be a solution.

**Comment by ccmadrid** [comment]
userId: 2814574886 
accessToken: 2814574886.24abbcd.b80472d0cab04414b9f58e319e124000

so here are the credentials for our instagram account
I tried following the steps, but no luck. I read somewhere that instagram just recently changed some API stuff and permission stuff. Maybe that's why it's not working, because the tutorials for installed are pretty straightforward

**Comment by ccmadrid** [comment]
@thomasjbradley I still can't get this to work. should we just scrap getting a live updated instagram feed? could you point me in a different direction to get something similar? I've tried and retried following tutorials with no success

**Comment by thomasjbradley** [comment]
Working on it…

**Comment by ccmadrid** [comment]
CliendId
24abbcdb173242dba04429796732ccd3

**Comment by ccmadrid** [comment]
new client id:
6cce6426afe248fcb95882aa746d64a5

**Comment by ccmadrid** [comment]
http://localhost/#access_token=2814574886.6cce642.50e0d6ddd24b4e9abfef4ead0b56dfae

**Comment by natalie-macpherson** [comment]
If the images are not working what are we going to have in its place?

**Comment by ccmadrid** [comment]
i just hid that section if there is no javascript. there are social media icons at the top anyways. reopen if you're unhappy with this change
