### ISSUE TITLE
Getting first name and last name using liquid filters

### ISSUE THREAD

**Issue by ccmadrid** [algonquindesign-grads/2016#62]
Instead of having to go into each md file and adding new items just for name stuff like the full_name, short_name, first and last, etc. we can use liquid filters in jekyll to get the first and last names. this will help get individual styling for like the medium page styling. and prevents us from having someone do a ton of grunt work and being extra careful with adding the new name items. Just seems a little counter productive. I think I know how to do this using http://cheat.jekyll.tips

**Comment by natalie-macpherson** [comment]
We can do this but people with middle initials or multiple middle names may not want to use a initial of one of the middle names over the first letter in their last name. From what Thomas stated on Tuesday it is best to just manually change the md files so we have more control of what is stated and are able to change the content if people are not happy with what content we put in that slot.
