### ISSUE TITLE
Left navigation too long on some screens

### ISSUE THREAD

**Issue by thomasjbradley** [algonquindesign-grads/2016#63]
The left column navigation is too long and gets cut off on some screens.
I haven't tested this on my MacBook Air, but I expect the problem will be worse there.

<img width="553" alt="screen shot 2016-02-26 at 12 49 37 pm" src="https://cloud.githubusercontent.com/assets/105192/13360516/9f2ac156-dc87-11e5-9f70-c2bcbdadcb2f.png">

**Comment by ccmadrid** [comment]
I just resized the text and got people to test. should be ok for now, but if not we can reopen this!
