### ISSUE TITLE
Image alignment

### ISSUE THREAD

**Issue by thomasjbradley** [algonquindesign-grads/2016#64]
I feel like these images should align with the name, it matches the space on the other side where the person’s photo will be.

<img width="252" alt="screen shot 2016-02-26 at 12 51 34 pm" src="https://cloud.githubusercontent.com/assets/105192/13360563/d134f626-dc87-11e5-9484-b2512dd98fb4.png">

**Comment by annamisak** [comment]
I will add padding when I work on the inside page file

**Comment by annamisak** [comment]
@thomasjbradley  I have double checked the high fidelity wireframe for the inside page, actually there is no white space between the images and the side nav. 

<img width="1292" alt="screen shot 2016-02-26 at 1 34 56 pm" src="https://cloud.githubusercontent.com/assets/6360209/13361644/f2d33b66-dc8d-11e5-8050-6d8ad8d50d30.png">

**Comment by thomasjbradley** [comment]
Okay, but does it feel weird that the person’s photo doesn't align properly with anything?

**Comment by annamisak** [comment]
I see your point. 

In the wireframe desktop image, there, I actually prefer not to have the person's photo flushed against the side of the page and the other images. It creates a separation from the rest which I think it looks nice. In the code I actually removed the top padding and aligned properly with the pictures.

However, when it is viewed on a smaller device it looks rather out of place a bit.

My suggestion is, perhaps when the student's photo is under the images (ex: wireframe 1 & 2 in the picture above), then the only padding to have is above the image and nothing to the left and right. That way the image will perfectly align with the image above it. I think that would look better. What do you think?

**Comment by thomasjbradley** [comment]
This is what I'm thinking:

![grad-alignment](https://cloud.githubusercontent.com/assets/105192/13362381/0cae60fc-dc92-11e5-857f-af1656ddaae7.jpg)

Make it always the same dimensions as the portfolio pieces but separate it a little.
- On small and medium screens there's a space above the person.
- On large there's a space beside the person, but their photo touches the right side of the screen to mimic how the pieces touch the nav on the left.

**Comment by annamisak** [comment]
Yes, it diffinetly looks better this way. I will adjust the spacing around the student's photo. Thanks Thomas.

**Comment by annamisak** [comment]
This has been fixed :)
