### ISSUE TITLE
Dots missing…?

### ISSUE THREAD

**Issue by thomasjbradley** [algonquindesign-grads/2016#65]
Should the grid dots be up behind the person’s name too?

<img width="645" alt="screen shot 2016-02-26 at 12 53 46 pm" src="https://cloud.githubusercontent.com/assets/105192/13360613/10aa94b4-dc88-11e5-8ceb-e1e14e1017d0.png">

**Comment by annamisak** [comment]
Yes, I have noticed that too, which I meant to fix. I will remove the background color.
