### ISSUE TITLE
Issues with filter and video

### ISSUE THREAD

**Issue by natalie-macpherson** [algonquindesign-grads/2016#73]
Can you help Christian and I with the drop-down menu for the filter and making the video controls work for the header video.

@thomasjbradley

**Comment by thomasjbradley** [comment]
Video fixed in #74

**Comment by natalie-macpherson** [comment]
It seems like the video is still not working once I merged your content into gh-pages. I hope I didn't do something wrong because I was working on mixins and some other styling things.

**Comment by thomasjbradley** [comment]
I just merged my filter too—the video is working here:
https://algonquindesign-grads.github.io/2016/
