### ISSUE TITLE
Effra Typekit font not loading on mobile

### ISSUE THREAD

**Issue by ccmadrid** [algonquindesign-grads/2016#9]
I'm looking into this, but it's really ugly on mobile right now because the custom typeface is not loading on mobile (specifically testing iPhone 5s Safari)

**Comment by thomasjbradley** [comment]
Hmm... what URL are you looking at it with?
Maybe I need to add that as an allowed URL to my Typekit.

**Comment by ccmadrid** [comment]
http://algonquindesign-grads.github.io/2016/
this is the url that I used to view on my phone and there devices. otherwise I'm using localhost stuff

**Comment by thomasjbradley** [comment]
Okay, that URL is now added to Typekit—should start working on mobile.

**Comment by ccmadrid** [comment]
awesome! works!! I've been working nonstop since like midnight! It's just so exciting that it's finally coming together. so satisfying
